version: "3.8"
services:
  server:
    stdin_open: true
    container_name: server
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT} --debug --reload-dir /app --log-level debug
    build:
      context: ./server/
      dockerfile: Dockerfile
    environment:
      - GUNICORN_CMD_ARGS=--reload
    volumes:
      - "./server/:/app"
    ports:
      - ${PORT}:${PORT}