version: "3.8"
services:
  server:
    stdin_open: true
    container_name: soda_net_model
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT} --debug --reload-dir /app --log-level debug
    build:
      context: ./server/
      dockerfile: Dockerfile
    environment:
      - GUNICORN_CMD_ARGS=--reload
    volumes:
      - "./server/:/app"
      - images:/app/images
    ports:
      - ${PORT}:${PORT}

volumes:
  images:
    external:
      name: photoanalysisserver_images